apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: alertmanager-config
  labels:
    app: alertmanager-config
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
