apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/path: '/metrics'
    prometheus.io/probe: 'true'
  labels:
    name: blackbox-exporter
  name: blackbox-exporter
spec:
  selector:
    app: blackbox-exporter
  type: NodePort
  ports:
  - name: blackbox-exporter
    protocol: TCP
    port: 9115
    targetPort: 9115
