apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: blackbox-exporter
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blackbox-exporter
  template:
    metadata:
      labels:
        app: blackbox-exporter
      annotations:
        prometheus.io/port: "9115"
        prometheus.io/scrape: "true"
        prometheus.io/path: "/metrics"
        prometheus.io/probe: "true"
    spec:
      containers:
      - image: prom/blackbox-exporter:v0.12.0
        name: blackbox-exporter
        ports:
        - containerPort: 9115
          name: metrics
