apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    name: influxdb-remote-storage
  name: influxdb-remote-storage
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      name: influxdb-remote-storage
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        name: influxdb-remote-storage
      annotations:
        prometheus.io/port: "9201"
        prometheus.io/scrape: "true"
        prometheus.io/path: "/metrics"
        prometheus.io/probe: "true"
    spec:
      containers:
      - env:
        - name: INFLUXDB_URL
          value: http://localhost:8086/
        - name: INFLUXDB_DATABASE
          value: prometheus
        - name: INFLUXDB_RETENTION_POLICY
          value: autogen
        - name: INFLUXDB_USER
          value: prom
        - name: INFLUXDB_PW
          value: prom
        image: b1systems/prometheus-influxdb-remote-storage:1.0
        imagePullPolicy: IfNotPresent
        name: influxdb-remote-storage
        ports:
        - containerPort: 9201
          protocol: TCP
      restartPolicy: Always
      securityContext: {}
      terminationGracePeriodSeconds: 30
