apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/path: "/metrics"
    prometheus.io/probe: "true"
    prometheus.io/scrape: "true"
  name: influxdb-remote-storage
  namespace: monitoring
spec:
  ports:
  - port: 9201
    protocol: TCP
    targetPort: 9201
  selector:
    name: influxdb-remote-storage
  type: NodePort
