apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prometheus-config
  labels:
    app: prometheus-config
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
